name:                haskell-backend
version:             0.1.0.0
github:              "githubuser/haskell-backend"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-backend#readme>

dependencies:
- base >=4.6.0.0 && <4.17

library:
  source-dirs: src

executables:
  haskell-backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-backend
    - aeson >=1.4.1.0 && <1.6 || >=2.0.0.0 && <2.1
    - servant 
    - servant-server
    - rel8
    
tests:
  haskell-backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-backend
